services:
  backend:
    build:
      context: .
      dockerfile: StoreWebAPI/Dockerfile
      args:
        BUILD_CONFIGURATION: Debug
    image: store.webapi
    ports:
      - "80:8080"
    env_file:
      - backend.env
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:8080"
    depends_on:
      - db
  db:
    image: mysql:latest
    env_file:
      - db.env
    ports:
      - "3306:3306"
